### PR TITLE
Exclude well-known empty entities

### LINKED ISSUE #24: Exclude well-known empty entities
Adding `/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn` (empty unixfs dir)  bricks Kubo, daemon is unable to start:

```
2023-10-19T19:51:49.062+0200	WARN	nopfs	nopfs@v0.0.12-0.20231012170252-ab19c8a36941/denylist.go:169	Opening /home/lidel/tmp/ttl-ipns-repo/denylists/text.deny: empty header
2023-10-19T19:51:49.063+0200	INFO	nopfs	nopfs@v0.0.12-0.20231012170252-ab19c8a36941/denylist.go:170	Processing /home/lidel/tmp/ttl-ipns-repo/denylists/text.deny: text.deny (No header found) by unknown
2023-10-19T19:51:49.063+0200	DEBUG	nopfs	nopfs@v0.0.12-0.20231012170252-ab19c8a36941/denylist.go:431	text.deny:1: IPFS rule. Key: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn. Entry: Path: (empty). Prefix: false. AllowRule: false.
2023-10-19T19:51:49.063+0200	DEBUG	nopfs	nopfs@v0.0.12-0.20231012170252-ab19c8a36941/denylist.go:783	IsCidBlocked load: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
2023-10-19T19:51:49.063+0200	DEBUG	nopfs	nopfs@v0.0.12-0.20231012170252-ab19c8a36941/entry.go:38	check-path:  matches
2023-10-19T19:51:49.063+0200	ERROR	core	core/builder.go:158	constructing the node: could not build arguments for function "reflect".makeFuncStub (reflect/asm_amd64.s:28): failed to build *mfs.Root: received non-nil error from function "github.com/ipfs/kubo/core/node".Files (github.com/ipfs/kubo/core/node/core.go:136): failure writing to dagstore: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn is blocked and cannot be provided

Error: constructing the node (see log for full detail): failure writing to dagstore: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn is blocked and cannot be provided
```

In practice, there is a short set of well-known empty CIDs that should never be blocked:
- empty unixfs directory 
  - `QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn`
  - `bafyaabakaieac` (inlined)
- empty block
  - raw:   `bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku`
  - inlined raw: `bafkqaaa`
  - dag-pb: `QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH`
  - dag-cbor: `bafyreigbtj4x7ip5legnfznufuopl4sg4knzc2cof6duas4b3q2fy6swua`
  - dag-json: `baguqeeraiqjw7i2vwntyuekgvulpp2det2kpwt6cd7tx5ayqybqpmhfk76fa`

@hsanjuan thoughts? would it be feasible to keep a safelist that overrides denylists, or are we ok with the footgun? (feature, not a bug)

### PR DESCRIPTION
**Pull request by hsanjuan**
Fixes #24.

### CODE REVIEW

File: tester/tester.go [hunk 1]
```diff
@@ -133,22 +133,34 @@ hints:
...
+
+	// rule14
+	allowCids := []cid.Cid{
+		cid.MustParse("QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn"),
+		cid.MustParse("bafyaabakaieac"),
+		cid.MustParse("bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku"),
+		cid.MustParse("bafkqaaa"),
+		cid.MustParse("QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH"),
+		cid.MustParse("bafyreigbtj4x7ip5legnfznufuopl4sg4knzc2cof6duas4b3q2fy6swua"),
+		cid.MustParse("baguqeeraiqjw7i2vwntyuekgvulpp2det2kpwt6cd7tx5ayqybqpmhfk76fa"),
```
Comment (hsanjuan) [inline tester/tester.go:150]: Not I'm not referencing nopfs.SafeCids here so that the testing module remains fully independent from nopfs, as perhaps one day it can test other implementations.

**Review by lidel — APPROVED** [review]
